name: Setup Rust Action Environment

description: Installs dependencies to run Rust jobs.

inputs:
  components:
    description: Components to install in the rust toolchain
    required: false
    default: ""
  channel:
    description: The Rust channel release to use
    required: false
    default: "stable"
  prefix-key:
    description: The prefix key for the rust cache
    required: false
    default: "v0-rust"

runs:
  using: "composite"
  steps:
    - name: Install Just
      uses: taiki-e/install-action@just

    - name: Install mold linker
      uses: rui314/setup-mold@v1

    - name: Installs stable rust toolchain
      if: ${{ inputs.channel == 'stable' && inputs.components == '' }}
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.86

    - name: Installs stable rust toolchain
      if: ${{ inputs.channel == 'stable' && inputs.components != '' }}
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.86
        components: ${{ inputs.components }}

    - name: Installs nightly rust toolchain
      if: ${{ inputs.channel == 'nightly' && inputs.components == '' }}
      uses: dtolnay/rust-toolchain@nightly

    - name: Installs nightly rust toolchain
      if: ${{ inputs.channel == 'nightly' && inputs.components != '' }}
      uses: dtolnay/rust-toolchain@nightly
      with:
        components: ${{ inputs.components }}

    - name: Installs the rust cache
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true
        prefix-key: ${{ inputs.prefix-key }}
        save-if: ${{ github.ref == 'refs/heads/main' }}
