name: Kurtosis E2E Tests Supervisor
on:
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
jobs:
  kurtosis-e2e-tests-supervisor:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    name: test
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.86
      - name: Setup Go 1.24.3
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.24.3'
      - uses: jdx/mise-action@v2       # installs Mise + runs `mise install`
      - name: test with simple-supervisor devnet
        env:
          DISABLE_OP_E2E_LEGACY: true
          DEVSTACK_ORCHESTRATOR: sysext
        # todo:: once the PR is merged, switch back to the ethpandaops/optimism-package
        # pr: https://github.com/ethpandaops/optimism-package/pull/343
        run: just build-devnet-and-test-e2e simple-supervisor supervisor github.com/dhyaniarun1993/optimism-package@kona-supervisor
