name: Kurtosis E2E Tests
on:
  push:
    branches: [main]
  merge_group:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  node-e2e-kurtosis-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    name: ${{ matrix.devnet-config }}-tests
    strategy:
      fail-fast: false
      matrix:
        devnet-config: ["simple-kona", "simple-kona-geth", "large-kona", "simple-kona-sequencer", "large-kona-sequencer", "simple-kona-conductor", "first-kona-conductor"]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          large-packages: false

      - uses: taiki-e/install-action@just

      - uses: jdx/mise-action@v3       # installs Mise + runs `mise install`

      - name: Setup Go 1.24.3
        uses: actions/setup-go@v6
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.24.3'
          cache-dependency-path: "**/go.sum"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore Docker cache
        uses: actions/cache/restore@v4
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build kona node docker image
        uses: docker/bake-action@v6
        env:
          BIN_TARGET: kona-node
          BUILD_PROFILE: release
          REPO_LOCATION: local
          PLATFORMS: linux/${{ runner.arch == 'X64' && 'amd64' || runner.arch == 'ARM64' && 'arm64' || runner.arch }}
        with:
          files: |
            ./docker/docker-bake.hcl
          load: true
          targets: |
            generic
          set: |
            *.tags=kona-node:local
            *.cache-from=type=local,src=${{ runner.temp }}/.buildx-cache
            *.cache-to=type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max

      - name: deploy devnet
        run: just devnet "${{ matrix.devnet-config }}"

      - name: common tests for node with ${{ matrix.devnet-config }} devnet
        run: just test-e2e-kurtosis "${{ matrix.devnet-config }}" node/common

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache

      - name: Save docker cache
        uses: actions/cache/save@v4
        if: github.ref == 'refs/heads/main'
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
